server:
  port: 8006

spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    enabled: true

user-service:
  url: http://localhost:8005

management:
  server:
    port: 8006
    address: 0.0.0.0
  endpoints:
    web:
      exposure:
        include: ['health', 'info', 'metrics', 'prometheus']